export interface SellerModuleDefinition {
  key: string;
  label: string;
  path: string;
  group: 'Overview' | 'Sales & POS' | 'Catalog & Inventory' | 'Reports' | 'Finance' | 'Settings';
  description: string;
  isEssential?: boolean;
}

export const ESSENTIAL_SELLER_MODULE_KEYS = ['dashboard', 'subscriptions'] as const;

export const ALL_SELLER_MODULES: SellerModuleDefinition[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    path: '/seller',
    group: 'Overview',
    description: 'Store analytics, live summary, and dashboard stats',
    isEssential: true,
  },
  {
    key: 'orders',
    label: 'Orders',
    path: '/seller/orders/all',
    group: 'Sales & POS',
    description: 'Manage all customer orders (Pending, Received, Processed, Shipped, Delivered, Cancelled)',
  },
  {
    key: 'requests',
    label: 'Requests',
    path: '/seller/return-requests',
    group: 'Sales & POS',
    description: 'Customer return and replacement requests',
  },
  {
    key: 'pos',
    label: 'POS System',
    path: '/seller/pos/orders',
    group: 'Sales & POS',
    description: 'POS Billing counter, POS orders, quotations, purchase reports & supplier ledger',
  },
  {
    key: 'manage-staff',
    label: 'Manage Staff',
    path: '/seller/manage-staff',
    group: 'Overview',
    description: 'Staff accounts, roles, commission and permissions',
  },
  {
    key: 'staff-bill-report',
    label: 'Staff Bill Report',
    path: '/seller/staff-bill-report',
    group: 'Reports',
    description: 'Sales and billing reports generated by staff members',
  },
  {
    key: 'category',
    label: 'Category',
    path: '/seller/category',
    group: 'Catalog & Inventory',
    description: 'View and request store product categories',
  },
  {
    key: 'subcategory',
    label: 'SubCategory',
    path: '/seller/subcategory',
    group: 'Catalog & Inventory',
    description: 'View and manage subcategories',
  },
  {
    key: 'attribute-setup',
    label: 'Attribute Setup',
    path: '/seller/product/attribute-setup',
    group: 'Catalog & Inventory',
    description: 'Custom product attributes and specifications',
  },
  {
    key: 'variation-setup',
    label: 'Variation Setup',
    path: '/seller/product/variation-setup',
    group: 'Catalog & Inventory',
    description: 'Variation types and value combinations',
  },
  {
    key: 'storage-location',
    label: 'Storage Location Setup',
    path: '/seller/product/storage-location',
    group: 'Catalog & Inventory',
    description: 'Warehouse, room and rack management for inventory',
  },
  {
    key: 'product',
    label: 'Product',
    path: '/seller/product/list',
    group: 'Catalog & Inventory',
    description: 'Add products, product list, taxes and stock management',
  },
  {
    key: 'reports',
    label: 'Reports',
    path: '/seller/reports/order',
    group: 'Reports',
    description: 'Order reports, invoice reports, GST sales reports, sales summaries & inventory reports',
  },
  {
    key: 'subscriptions',
    label: 'Subscriptions',
    path: '/seller/subscriptions',
    group: 'Finance',
    description: 'Seller subscription plans, category access and renewal status',
    isEssential: true,
  },
  {
    key: 'wallet',
    label: 'Wallet',
    path: '/seller/wallet/transactions',
    group: 'Finance',
    description: 'Seller earnings wallet, transactions and withdrawal requests',
  },
  {
    key: 'brand-settings',
    label: 'Brand Settings',
    path: '/seller/account-settings?tab=branding',
    group: 'Settings',
    description: 'Store logo, banner, theme branding and store details',
  },
  {
    key: 'delivery-settings',
    label: 'Delivery Settings',
    path: '/seller/delivery-settings',
    group: 'Settings',
    description: 'Delivery radius, fees, serviceable locations and options',
  },
  {
    key: 'payment-list',
    label: 'Payment List',
    path: '/seller/reports/payment',
    group: 'Finance',
    description: 'Customer payments and transaction ledger',
  },
  {
    key: 'other-configurations',
    label: 'Other Configurations',
    path: '/seller/app-settings',
    group: 'Settings',
    description: 'Store app preferences and configurations',
  },
  {
    key: 'shiprocket-integration',
    label: 'Shiprocket Integration',
    path: '/seller/app-settings?tab=shiprocket',
    group: 'Settings',
    description: 'Courier and Shiprocket logistics integration',
  },
  {
    key: 'sms-gateway',
    label: 'SMS Gateway',
    path: '/seller/sms-gateway',
    group: 'Settings',
    description: 'SMS notification gateway settings',
  },
  {
    key: 'product-settings',
    label: 'Product Settings',
    path: '/seller/product-display-settings',
    group: 'Settings',
    description: 'Product display rules, card options and listing settings',
  },
  {
    key: 'bill-settings',
    label: 'Bill Settings',
    path: '/seller/bill-settings',
    group: 'Settings',
    description: 'POS invoice formatting, bill headers and print options',
  },
  {
    key: 'barcode-settings',
    label: 'Barcode Settings',
    path: '/seller/barcode-settings',
    group: 'Settings',
    description: 'Barcode generator, label dimensions and print settings',
  },
];

export const ALL_SELLER_MODULE_KEYS = ALL_SELLER_MODULES.map((m) => m.key);

export const MODULE_LABEL_TO_KEY: Record<string, string> = {
  "Dashboard": "dashboard",
  "Orders": "orders",
  "Requests": "requests",
  "POS System": "pos",
  "Manage Staff": "manage-staff",
  "Staff Bill Report": "staff-bill-report",
  "Category": "category",
  "SubCategory": "subcategory",
  "Attribute Setup": "attribute-setup",
  "Variation Setup": "variation-setup",
  "Storage Location Setup": "storage-location",
  "Product": "product",
  "Reports": "reports",
  "Subscriptions": "subscriptions",
  "Wallet": "wallet",
  "Brand Settings": "brand-settings",
  "Delivery Settings": "delivery-settings",
  "Payment List": "payment-list",
  "Other Configurations": "other-configurations",
  "Shiprocket Integration": "shiprocket-integration",
  "SMS Gateway": "sms-gateway",
  "Product Settings": "product-settings",
  "Bill Settings": "bill-settings",
  "Barcode Settings": "barcode-settings",
};

export const SELLER_ACCESSIBILITY_UPDATED_EVENT = 'seller_accessibility_updated';
/** Fire after a seller buys / renews a plan so the panel re-reads what the plan unlocks */
export const SELLER_PLAN_CHANGED_EVENT = 'seller_plan_changed';

/**
 * Check if a module key or label is allowed based on accessibleModules list
 */
export function isSellerModuleAllowed(
  moduleKeyOrLabel: string,
  accessibleModules?: string[] | null
): boolean {
  const key = MODULE_LABEL_TO_KEY[moduleKeyOrLabel] || moduleKeyOrLabel.toLowerCase().trim();
  // Essential modules are always permitted
  if (key === 'dashboard' || key === 'subscriptions') {
    return true;
  }
  if (accessibleModules === null || accessibleModules === undefined) {
    return true; // Default to allow if permissions not yet loaded
  }
  return accessibleModules.includes(key);
}

/**
 * Resolve which seller module key corresponds to a given route pathname & search query
 */
export function getSellerModuleKeyForPath(pathname: string, search: string = ''): string | null {
  const cleanPath = pathname.replace(/\/$/, '') || '/seller';
  const query = new URLSearchParams(search);
  const tab = (query.get('tab') || query.get('section') || '').toLowerCase();

  // Root Dashboard
  if (cleanPath === '/seller') return 'dashboard';

  // Query-parameter specific tabs
  if (cleanPath === '/seller/account-settings') {
    if (tab === 'shiprocket') return 'shiprocket-integration';
    return 'brand-settings';
  }
  if (cleanPath === '/seller/app-settings') {
    if (tab === 'shiprocket') return 'shiprocket-integration';
    return 'other-configurations';
  }

  // Exact or prefix sub-routes
  if (cleanPath.startsWith('/seller/orders') || cleanPath.startsWith('/seller/order/')) return 'orders';
  if (cleanPath.startsWith('/seller/return-requests') || cleanPath.startsWith('/seller/replace-requests') || cleanPath.startsWith('/seller/requests')) return 'requests';
  if (cleanPath.startsWith('/seller/pos') || cleanPath.startsWith('/seller/purchase')) return 'pos';
  if (cleanPath.startsWith('/seller/manage-staff')) return 'manage-staff';
  if (cleanPath.startsWith('/seller/staff-bill-report')) return 'staff-bill-report';
  if (cleanPath.startsWith('/seller/category')) return 'category';
  if (cleanPath.startsWith('/seller/subcategory')) return 'subcategory';
  if (cleanPath.startsWith('/seller/product/attribute-setup')) return 'attribute-setup';
  if (cleanPath.startsWith('/seller/product/variation-setup')) return 'variation-setup';
  if (cleanPath.startsWith('/seller/product/storage-location')) return 'storage-location';
  if (cleanPath.startsWith('/seller/product')) return 'product';
  if (cleanPath.startsWith('/seller/reports/payment')) return 'payment-list';
  if (cleanPath.startsWith('/seller/reports') || cleanPath.startsWith('/seller/sales-summary') || cleanPath.startsWith('/seller/inventory-reports')) return 'reports';
  if (cleanPath.startsWith('/seller/subscriptions')) return 'subscriptions';
  if (cleanPath.startsWith('/seller/wallet')) return 'wallet';
  if (cleanPath.startsWith('/seller/delivery-settings')) return 'delivery-settings';
  if (cleanPath.startsWith('/seller/sms-gateway')) return 'sms-gateway';
  if (cleanPath.startsWith('/seller/product-display-settings')) return 'product-settings';
  if (cleanPath.startsWith('/seller/bill-settings')) return 'bill-settings';
  if (cleanPath.startsWith('/seller/barcode-settings')) return 'barcode-settings';

  return null;
}

/**
 * Check if the active seller route is permitted according to accessibleModules
 */
export function isSellerPathAllowed(
  pathname: string,
  search: string = '',
  accessibleModules?: string[] | null
): boolean {
  const moduleKey = getSellerModuleKeyForPath(pathname, search);
  if (!moduleKey) return true; // Non-restricted pages like profile/help
  // Essential modules (Dashboard & Subscriptions) are always accessible
  if (moduleKey === 'dashboard' || moduleKey === 'subscriptions') {
    return true;
  }
  if (accessibleModules === null || accessibleModules === undefined) {
    return true; // Not loaded yet
  }
  return accessibleModules.includes(moduleKey);
}
