export interface SellerModuleDefinition {
  key: string;
  label: string;
  path: string;
  group: 'Overview' | 'Sales & POS' | 'Catalog & Inventory' | 'Reports' | 'Finance' | 'Settings';
  description: string;
  isEssential?: boolean;
}

export const ESSENTIAL_SELLER_MODULE_KEYS = ['dashboard', 'subscriptions'] as const;

export const ALL_SELLER_MODULES: SellerModuleDefinition[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    path: '/seller',
    group: 'Overview',
    description: 'Store analytics, live summary, and dashboard stats',
    isEssential: true,
  },
  {
    key: 'orders',
    label: 'Orders',
    path: '/seller/orders/all',
    group: 'Sales & POS',
    description: 'Manage all customer orders (Pending, Received, Processed, Shipped, Delivered, Cancelled)',
  },
  {
    key: 'requests',
    label: 'Requests',
    path: '/seller/return-requests',
    group: 'Sales & POS',
    description: 'Customer return and replacement requests',
  },
  {
    key: 'pos',
    label: 'POS System',
    path: '/seller/pos/orders',
    group: 'Sales & POS',
    description: 'POS Billing counter, POS orders, quotations, purchase reports & supplier ledger',
  },
  {
    key: 'manage-staff',
    label: 'Manage Staff',
    path: '/seller/manage-staff',
    group: 'Overview',
    description: 'Staff accounts, roles, commission and permissions',
  },
  {
    key: 'staff-bill-report',
    label: 'Staff Bill Report',
    path: '/seller/staff-bill-report',
    group: 'Reports',
    description: 'Sales and billing reports generated by staff members',
  },
  {
    key: 'category',
    label: 'Category',
    path: '/seller/category',
    group: 'Catalog & Inventory',
    description: 'View and request store product categories',
  },
  {
    key: 'subcategory',
    label: 'SubCategory',
    path: '/seller/subcategory',
    group: 'Catalog & Inventory',
    description: 'View and manage subcategories',
  },
  {
    key: 'attribute-setup',
    label: 'Attribute Setup',
    path: '/seller/product/attribute-setup',
    group: 'Catalog & Inventory',
    description: 'Custom product attributes and specifications',
  },
  {
    key: 'variation-setup',
    label: 'Variation Setup',
    path: '/seller/product/variation-setup',
    group: 'Catalog & Inventory',
    description: 'Variation types and value combinations',
  },
  {
    key: 'storage-location',
    label: 'Storage Location Setup',
    path: '/seller/product/storage-location',
    group: 'Catalog & Inventory',
    description: 'Warehouse, room and rack management for inventory',
  },
  {
    key: 'product',
    label: 'Product',
    path: '/seller/product/list',
    group: 'Catalog & Inventory',
    description: 'Add products, product list, taxes and stock management',
  },
  {
    key: 'reports',
    label: 'Reports',
    path: '/seller/reports/order',
    group: 'Reports',
    description: 'Order reports, invoice reports, GST sales reports, sales summaries & inventory reports',
  },
  {
    key: 'subscriptions',
    label: 'Subscriptions',
    path: '/seller/subscriptions',
    group: 'Finance',
    description: 'Seller subscription plans, category access and renewal status',
    isEssential: true,
  },
  {
    key: 'wallet',
    label: 'Wallet',
    path: '/seller/wallet/transactions',
    group: 'Finance',
    description: 'Seller earnings wallet, transactions and withdrawal requests',
  },
  {
    key: 'brand-settings',
    label: 'Brand Settings',
    path: '/seller/account-settings?tab=branding',
    group: 'Settings',
    description: 'Store logo, banner, theme branding and store details',
  },
  {
    key: 'delivery-settings',
    label: 'Delivery Settings',
    path: '/seller/delivery-settings',
    group: 'Settings',
    description: 'Delivery radius, fees, serviceable locations and options',
  },
  {
    key: 'payment-list',
    label: 'Payment List',
    path: '/seller/reports/payment',
    group: 'Finance',
    description: 'Customer payments and transaction ledger',
  },
  {
    key: 'other-configurations',
    label: 'Other Configurations',
    path: '/seller/app-settings',
    group: 'Settings',
    description: 'Store app preferences and configurations',
  },
  {
    key: 'shiprocket-integration',
    label: 'Shiprocket Integration',
    path: '/seller/app-settings?tab=shiprocket',
    group: 'Settings',
    description: 'Courier and Shiprocket logistics integration',
  },
  {
    key: 'sms-gateway',
    label: 'SMS Gateway',
    path: '/seller/sms-gateway',
    group: 'Settings',
    description: 'SMS notification gateway settings',
  },
  {
    key: 'product-settings',
    label: 'Product Settings',
    path: '/seller/product-display-settings',
    group: 'Settings',
    description: 'Product display rules, card options and listing settings',
  },
  {
    key: 'bill-settings',
    label: 'Bill Settings',
    path: '/seller/bill-settings',
    group: 'Settings',
    description: 'POS invoice formatting, bill headers and print options',
  },
  {
    key: 'barcode-settings',
    label: 'Barcode Settings',
    path: '/seller/barcode-settings',
    group: 'Settings',
    description: 'Barcode generator, label dimensions and print settings',
  },
];

export const ALL_SELLER_MODULE_KEYS = ALL_SELLER_MODULES.map((m) => m.key);
